# Site settings
title: Your awesome title
username: yourname
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
paginate_path: "/page:num/"

# Comment thread setting
disqus_forumname: tranquil-theme